server:
  port: 8080
spring:
  application:
    name: "credi-ya"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: users_db
    schema: public
    username: admin
    password: admin123
    pool:
      initial-size: 5
      max-size: 20
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
