server:
  port: 8080
spring:
  application:
    name: "credi-ya"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
adapters:
  r2dbc:
    host: localhost
    port: 5432
    database: users_db
    schema: public
    username: admin
    password: admin123
    pool:
      initial-size: 5
      max-size: 20
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    enabled: true
    url: /v3/api-docs/public-apis
    tags-sorter: alpha
    doc-expansion: none
    try-it-out-enabled: true
  show-actuator: true
  cache:
    disabled: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  model-and-view-allowed: false
  override-with-generic-response: false
  use-fqn: false
